// <auto-generated />
namespace MyConcert.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createrolesandadmin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createrolesandadmin));
        
        string IMigrationMetadata.Id
        {
            get { return "201704191304209_create-roles-and-admin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
