// <auto-generated />
namespace MyConcert.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _3421 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3421));
        
        string IMigrationMetadata.Id
        {
            get { return "201704200855352_3421"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
